# syntax=docker/dockerfile:1

FROM golang:1.22-alpine AS builder
WORKDIR /build
RUN apk add --no-cache git ca-certificates
COPY hi-im-api /build/hi-im-api
COPY hi-im-hubclient /build/hi-im-hubclient
COPY hi-im-usrsvr /build/hi-im-usrsvr
WORKDIR /build/hi-im-usrsvr
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o /usrsvr ./cmd/usrsvr

FROM alpine:3.20
RUN apk add --no-cache ca-certificates wget
COPY --from=builder /usrsvr /usr/local/bin/usrsvr
EXPOSE 8081
ENTRYPOINT ["/usr/local/bin/usrsvr"]
